FROM python:3.11

RUN pip install --upgrade pip  \
    && pip install "poetry==1.6.1"  \
    && poetry config virtualenvs.create false

WORKDIR /api_movie_app

COPY ["poetry.lock", "pyproject.toml", "./"]

RUN poetry install --no-root --no-interaction --with tests

WORKDIR /app

COPY app .

WORKDIR /api_movie_app

COPY tests .

CMD ["pytest"]
